apiVersion: v1
kind: ConfigMap
metadata:
  name: targeting-service-config
  namespace: targeting-service
data:
  PORT: "8003"
  AUTH_SERVICE_URL: "http://auth-service.auth-service.svc.cluster.local:8001"
