apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: analytics-service-secrets
  namespace: analytics-service
spec:
  refreshInterval: 30s
  secretStoreRef:
    name: aws-secrets-manager
    kind: ClusterSecretStore
  target:
    name: analytics-service-secrets
    creationPolicy: Owner
  dataFrom:
    - extract:
        key: eks/analytics-service
