apiVersion: v1
kind: Service
metadata:
  name: analytics-service
  namespace: analytics-service
  labels:
    app: analytics-service
spec:
  type: ClusterIP
  selector:
    app: analytics-service
  ports:
    - name: http
      port: 8005
      targetPort: 8005
