apiVersion: keda.sh/v1alpha1
kind: TriggerAuthentication
metadata:
  name: analytics-service-aws-auth
  namespace: analytics-service
spec:
  secretTargetRef:
    - parameter: awsAccessKeyID
      name: aws-credentials
      key: access-key
    - parameter: awsSecretAccessKey
      name: aws-credentials
      key: secret-access-key
    - parameter: awsSessionToken
      name: aws-credentials
      key: session-token
