name: CI — targeting-service

on:
  push:
    branches: [main]
    paths:
      - "targeting-service/**"
  pull_request:
    branches: [main]
    paths:
      - "targeting-service/**"

jobs:
  ci:
    uses: ./.github/workflows/_ci-python.yml
    with:
      service: targeting-service
      ecr_repo: targeting-service
    secrets: inherit
